### ISSUE TITLE
NeoVimだと動かない…

### ISSUE THREAD

**Issue by iwata** [po3rin/vim-gofmtmd#3]
`gofmtmd`便利で使わせてもらっています!
`job_start`がNeoVimだと`jobstart`を使う必要があるっぽいです。
ref. https://qiita.com/abekoh/items/707a589dadf571dbc390
可能ならNeoVimもサポートしてほしいですが、難しそうならREADMEに書いてもらえると…!

**Comment by po3rin** [comment]
issueありがとうございます。NeoVimに詳しくないのですが、対応すべき点は見た所```job_start```だけでしょうか？これだけであればVimかNeoVimかで判定して使う関数を出し分ける形で対応します。

**Comment by po3rin** [comment]
とりあえずPRを作りました。動作確認出来次第マージする予定です。
#4

**Comment by po3rin** [comment]
#5 でテストを追加したらそもそも動かなたったので、少し修正します。

**Comment by po3rin** [comment]
#4 で nvim 環境でテストが通ることを確認してmergeしました。いかがでしょうか。

**Comment by po3rin** [comment]
間違えて閉じてしまいました。

**Comment by iwata** [comment]
いけました!
ちなみに`GoFmtMd`を実行するとファイルリロードしないとformatされた結果が反映されなかったんですが、それはそういう仕様でしょうか?
このissue自体は閉じますね。

**Comment by po3rin** [comment]
それもneovim固有の問題、もしくは設定周りの問題な気がしますね。。
僕は明示的にリロードせずに反映できています。

コードとしては下記の箇所でリロードをしています。
https://github.com/po3rin/vim-gofmtmd/blob/master/autoload/gofmtmd.vim#L20
